### ISSUE TITLE
Coffee Recipe error? (questions... how to set up recipes, etc)

### ISSUE THREAD

**Issue by mrcoffee1026** [DieReicheErethons/Brewery#155]
this Is from the default config see:
```
   10:
      name: Stale Coffee/Coffee/Strong Coffee
      ingredients:
      - INK_SACK,3/12
      - MILK_BUCKET/2
      cookingtime: 2
      color: BLACK
      difficulty: 3
      effects:
      - REGENERATION/1/2-5
      - SPEED/1/30-140

```
Along with:
```
cooked:
   WHEAT: Fermented wheat
   SUGAR_CANE: Sugar brew
   APPLE: Apple cider
   POTATO_ITEM: Potatomash
   LONG_GRASS: Boiled herbs
   RED_MUSHROOM: Mushroom brew
   INK_SACK: Colored brew
   MILK_BUCKET: Milky water


```

These 2 lists should make coffee un-brewable.  INK_SACK is the ancientified ID of the black ink sack (dropped from squids).  If you use this item, you will produce a "colored brew" which is useful for exactly nothing.  This item + the required milks... also makes "colored brew".  Interestingly, using a... closest equivalent ancientified ID I can think of here would be "BROWN_INK_SACK" instead, WILL result in Coffee... my question is... WHY?  How does the plugin know to create this item given that it is... not asked for?  If I am to design my own recipes, it would seem to me that the IDs being used have to have a somewhat permanent and verifiable list to select these items from?  If the plugin does some sort of hard-coded converting and translating on its own at whatever whim, I don't see how to set these up properly?

Speaking of odd items... if you create an item such as "colored brew" in one step, how do you specify in a recipe to require that ingredient in a later step?  What ID does "colored brew" receive?  Is it possible to specify potion items and similar by their numeric ID for the recipe (example: 5:0 for oak wood planks)?  Ideally I'd like to integrate various SlimeFun ingredients into the beverages, but they're virtually all some variant of a Vanilla item.. with slight alterations to an ID that I... well frankly I don't see how this plugin is recognizing vanilla items since there isn't a consensus within the included config file, adding any more items seems to be rather impossible.  In any case, any explanation as to how/why the coffee recipe works the way it does might go a long way towards explaining how to form new recipes.  It would also be very helpful to know how the "difficulty" affected the item, if at all.

Thanks for any help on this.
