### ISSUE TITLE
Aging Time is in Minutes instead of "Minecraft Days"

### ISSUE THREAD

**Issue by Deiscorides** [DieReicheErethons/Brewery#25]
In the config.yml files it states:

"# age: Time in Minecraft-days, the potion has to age in a barrel 0=no aging"

Yet, it seems to only be in minutes. I have tons of recipes that have very long aging times like this:

```
  name: Blast Beer
  ingredients:
  - SLIME_BALL/10
  - CLAY_BALL/2
  - LEAVES/3
  - BLAZE_POWDER/8
  - FIREWORK_CHARGE/1
  cookingtime: 44
  wood: 3
  age: 35
  color: DARK_RED
  difficulty: 9
  alcohol: 25
```

Instead of taking 35 days in Minecraft it only takes 35 minutes. Is this an error? If it is, and you are able to correct it in an update, would the update make the old brews no longer work?
