### ISSUE TITLE
Adding brews to recipes

### ISSUE THREAD

**Issue by sadbri** [DieReicheErethons/Brewery#285]
This is the first plugin ive configured myself and so far it has work amazingly! However I’m having an issue with adding a brewery made brew as an ingredient for another brew. When I load the game it doesn’t state there are any issues however when adding the brew, in the case of the example below it was carrot soup, it just won’t add to the cauldron. 

Leepers-Leap:
    name: Peter Rabbit
    ingredients:
      - RABBIT_FOOT/5
      - COOKED_RABBIT/5
      - CARROT/10
      - Brewery:Carrot_soup/3
    cookingtime: 4
    color: ORANGE
    difficulty: 6
    lore: Its peter rabbit!
    effects:
      - JUMP/1/30

Is there something I’ve not worded somewhere correctly for this to happen. Thanks!

**Comment by mcgodbuild** [comment]
did you add the previous brew as a custom item? Add it as a ingredients? also you dont call it
- brewery:Carrot_soup/3 just call it - Carrot_soup/3

**Comment by Sn0wStorm** [comment]
@mcgodbuild You don't need to add the item as custom item, or any other thing. It will work just put it in a recipe. If it doesnt its a bug.

@sadbri Make sure the Carrot_soup recipe uses Carrot_soup as **middle** name (or only has one name) Also make sure the casing is correct, so no `Carrot_Soup` or `carrot_soup`

**Comment by mcgodbuild** [comment]
@Sn0wStorm It does not recognise the ingredient and after adding it as a material it gives ruined potion. Adding it as a custom lets it be made fine. IF you want to say its a bugg then its a major one affecting basicly all custom made recipes

**Comment by Sn0wStorm** [comment]
@mcgodbuild So i just tried with a **fresh** config and only added `- Brewery:Beer/1` to the Mead recipe.
Like this: 
```
  mead:
    name: Awkward Mead/Mead/&6Golden Mead
    ingredients:
      - Sugar_Cane/6
      - Brewery:Beer/1
    cookingtime: 3
    distillruns: 0
    wood: 2
    age: 4
    color: ORANGE
    difficulty: 2
    lore:
      - +++ Has a golden shine
    alcohol: 9
```

I didn't add anything else. And it works. Cauldron accepts Beer now and using Beer and Sugar Cane results in Mead.

Could you please try if that works the same for you?
