### ISSUE TITLE
usage of Brewery:

### ISSUE THREAD

**Issue by oguh43** [DieReicheErethons/Brewery#299]
How can i use tonic in a recipy if it is named like this:
```
tonic:
    name: '&bCLEVER Tonic/&eLidl Tonic/&6Billa Tonic'
```
i use this setup but cannot add tonic into the cauldron
```
gin_tonic:
    name: '&eGin&r &fTonic'
    ingredients:
        Brewery:&eLidl Tonic
        Brewery:Gin
    color: '00E0FF'
    cooktime: 2
    distillruns: 1
    distilltime: 60
    alcohol: 25
```
I want to be able to use all variants 1 to 5 star in the recipe
