### ISSUE TITLE
custom cauldron entries not going back in

### ISSUE THREAD

**Issue by DarkoPendragon** [DieReicheErethons/Brewery#304]
A server I'm on has been trying to create a Kahlua brew. We've added some custom entries to use with the cauldron for not just this brew, but other ones. Some work and some don't.
For instance:
```
  molasses:
    name: Molasses
    ingredients: Bedrock
    color: '#5e4602' # brown
    
  vanilla:
    name: Vanilla Bean Extract
    ingredients: Lily_of_the_valley
    color: '#FFFFFF' # white
```
We can make both of these perfectly fine. The molasses empties and goes back into the cauldron after taken out, however the extract will not. No errors I'm aware of.
