### ISSUE TITLE
[Question] Events with Alerts

### ISSUE THREAD

**Issue by thomaboehi** [DieReicheErethons/Brewery#336]
Hi.

Sorry to create an issue for that, but I tried to find a Discord, or somewhere to talk, couldn't find.

I really never got deeper in minecraft than basic plugin configuration.

I looked over the Brewery code, discovered the "events" so I tried a bit with DiscordSRV.

```yml
Alerts:
  - Trigger: BrewDrinkEvent
    Channel: global
    Embed:
      Color: "#ffffff"
      Author:
        ImageUrl: "https://cravatar.eu/helmhead/${player.name}/128.png"
        Name: "${player.name} a bu ${brew.currentRecipe}."
```

Looked fun, worked, but I couldn't manage to get something else than
`Heridien a bu BRecipe{Bière}.`
as what I want is:
`Heridien a bu Bière.`

What do I have to change?

Best regards!
