### ISSUE TITLE
[1.12.2] Mushrooms/Leaves/other blocks can't be put into the cauldron

### ISSUE THREAD

**Issue by TheGreatWeegee** [DieReicheErethons/Brewery#376]
Hello! I must say that your plugin works really wonderful, the only one issue that I have is that I can't add anything placeable (as blocks) into the cauldron, including mushrooms, leaves and other kind of stuff.
Can you in some way override it?
I've tried everything, from simply clicking it to re-defining the leaves/mushrooms as custom items and it didn't work.

I have something like this (I can't also add the bone meal, but I think it is the issue with Bukkit itself, since it doesn't have separate ID for bone meal, sadly :( )
```
  bone_meal:
    material:
        - INK_SACK
    name: 'Bone Meal'
    
  red_mushroom:
    material:
        - RED_MUSHROOM
    name: 'Mushroom'
    
  brown_mushroom:
    material:
        - BROWN_MUSHROOM
    name: 'Mushroom'
    
  leaves:
    material:
        - LEAVES
 ```
