### ISSUE TITLE
Suggestion: Add customModelData as customItems option in config.yml

### ISSUE THREAD

**Issue by Okmeis** [DieReicheErethons/Brewery#461]
For servers with multiple custom items realized by resource packs using customModelData, it'd be nice to be able to differentiate ingredients that way.

Example:
Server xyz has a resource pack with differrent fruits. Apples with customModelData 2 are oranges.

```
customItems:
  fruit-orange:
    material:
      - Apple
        -customModelData: 2

cauldron:
  abc:
    name: Orange Juice
    ingredients:
      - fruit-orange/2

  def:
    name: Apple Juice
    ingredients:
      - Apple/2
```
