### ISSUE TITLE
No cauldron particle color persistance after last color entry

### ISSUE THREAD

**Issue by aspwil** [DieReicheErethons/Brewery#490]
I'm not sure if this in an intentional feature or a bug, so I'm going to assume its a bug.

if you write in the config something like this
```YAML
dandelion_liquor_base:
    name: Dandelion Tea
    ingredients:
      - DANDELION
      - SUGAR
    color: 'FFBA26'
    cookParticles:
      - 'FFBA26/1'
    lore: '&8Tea, Brewed From A Dandelion'
```

then at 1 min of cook time the cauldron particles color turns to FFBA26 as expected,
but at 2 minutes the colors turn to white.

I assume it should stay the provided color (unless I'm misunderstanding the way in which the system works)
