### ISSUE TITLE
[Suggestion] permission for every recipe

### ISSUE THREAD

**Issue by DayzDuck** [DieReicheErethons/Brewery#522]
I would ask for the ability to add permission for each recipe you add.

either, the plugin automatically chooses the name of the recipe. OR that you build it into the recipe.

Permissions example:
```
  rote_betesaft:
    name: Schlechter Rote Betesaft/&8Rote Betesaft/&6Guter Rote Betesaft
    permission: rotebetesaft
    ingredients:
      - beetroot/4
      - sugar/1
    cookingtime: 2
    difficulty: 2
    alcohol: 0
    lore:
      - + Eine Flasche mit ungenießbarem Rote Betesaft
      - ++ Eine Flasche Rote Betesaft
      - +++ Eine Flasche mit geschmackvollem Rote Betesaft
    customModelData: 592
    effects:
      - REGENERATION/1-4
```
so the permissions would be:
`permissions.brew.rotebetesaft`

or the other variants, that he reads it out automatically. Then the permission would be:
`permissions.brew.rote_betesaft`
