### ISSUE TITLE
Slimefun Recipes

### ISSUE THREAD

**Issue by ItsStunik** [DieReicheErethons/Brewery#574]
Hi,
I would like to ask how can I create recipe that includes slimefun, like exotic garden items

Thank you.

**Comment by Fern-evergreen1** [comment]
You can, just look up the items ID and that should work, just have to specify the mod with the recipe iirc

**Comment by Vutka1** [comment]
Copied from plugin's config.yml:

```
# -- Recipes for Potions --

[...]
# ingredients: List of 'material/amount'
[...]
#  - Plugin items with 'plugin:id' (Currently supporting ExoticGarden, Slimefun, MMOItems, Brewery)
[...]
```
For example:
```
  example:
    name: Bad Example/Example/Good Example
    ingredients:
      - ExoticGarden:Grape/3
```
