### ISSUE TITLE
Potion Effects past 1311 seconds cause infinite Effect.

### ISSUE THREAD

**Issue by Deiscorides** [DieReicheErethons/Brewery#62]
Going past 1311 seconds in any potion effect causes the timer for the effect to have no numbers and the effects never run out (infinite effect time). It would be great if this did not happen. I'd like the option of giving potions 60 minutes of effects time, but currently, it gives infinite time if I try something past 1311.

Example image showing what the effects timer looks like:

http://i.imgur.com/DxnLwp1.jpg

Example recipe:

```
  name: God Beer
  ingredients:
  - SUGAR/1
  - SPECKLED_MELON/1
  cookingtime: 5
  color: BRIGHT_RED
  difficulty: 1
  effects:
  - FIRE_RESISTANCE/1312
  - INCREASE_DAMAGE/1312
  - SPEED/1312
  - JUMP/1312
  - REGENERATION/1312
  - DAMAGE_RESISTANCE/1312
```
