### ISSUE TITLE
tried to add some non-alchoholic drinks on my own and they dont work

### ISSUE THREAD

**Issue by rlxck** [DieReicheErethons/Brewery#637]
it was kinda rushed and i basically tried to copy some drinks that were already there
i just wanna know what im doing wrong and how to make them work because they all come out of the cauldron as brews that are already in the plugin, and when i try the rest of what i added it just turns to murky distillate

![image](https://github.com/user-attachments/assets/b60d855e-9fb8-42d3-949d-0d2f18de990b)
![image](https://github.com/user-attachments/assets/78bbffc6-a022-4a8b-9bae-44a0775eb482)
![image](https://github.com/user-attachments/assets/eb764068-88a6-4438-9b13-859489a89200)
![image](https://github.com/user-attachments/assets/81085e2c-0d2f-4e0f-bb22-35a3893205f8)
![image](https://github.com/user-attachments/assets/c450051a-6b43-47a5-836b-27acf5127ced)
![image](https://github.com/user-attachments/assets/4ee92d0e-c06d-4415-804d-227474b9b545)
thats all i added, lmk what i should do

**Comment by Grrevous** [comment]
Did you add these to all proper sections? There's 'Custom Items', 'Cauldron', and 'Recipe' sections that all have to have the specific layout. If not, the plugin could get confused as to which drink you're making.

**Comment by rlxck** [comment]
in my config theres only cauldron and recipe, the last two pictures are on cauldron and the rest are in recipes

**Comment by Dude-MC** [comment]
You have incorrect spacing. You need to have 1 tab before recipe id, then colon and with 2 tabs the recipe. Here is what you have vs how it should be:
```
  fanta:
  name: Lean Fanta/American Fanta/Grape Fanta
  ingredients: 
  - Sweet_berries/4
  - Sugar/3
  cookingtime: 2
  distillruns: 2
  color: RED
  ...
```
Here is how it should be:
```
  fanta:
    name: Lean Fanta/American Fanta/Grape Fanta
    ingredients: 
      - Sweet_berries/4
      - Sugar/3
    cookingtime: 2
    distillruns: 2
    color: RED
  ...
```
  Also, when you are creating a list(like ingredients), all things in it should have 1 extra tab
